// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: strmprivacy/api/data_policies/v1alpha/data_policies_v1alpha.proto

package data_policies

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Target_TargetType int32

const (
	Target_TARGET_TYPE_UNSPECIFIED Target_TargetType = 0
	Target_DATABRICKS_DYNAMIC_VIEW Target_TargetType = 1
)

// Enum value maps for Target_TargetType.
var (
	Target_TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "DATABRICKS_DYNAMIC_VIEW",
	}
	Target_TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"DATABRICKS_DYNAMIC_VIEW": 1,
	}
)

func (x Target_TargetType) Enum() *Target_TargetType {
	p := new(Target_TargetType)
	*p = x
	return p
}

func (x Target_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_enumTypes[0].Descriptor()
}

func (Target_TargetType) Type() protoreflect.EnumType {
	return &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_enumTypes[0]
}

func (x Target_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target_TargetType.Descriptor instead.
func (Target_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{2, 0}
}

type Schema_Type int32

const (
	Schema_TYPE_UNSPECIFIED Schema_Type = 0
	Schema_SQL_DDL          Schema_Type = 1
	Schema_DBT              Schema_Type = 2
)

// Enum value maps for Schema_Type.
var (
	Schema_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "SQL_DDL",
		2: "DBT",
	}
	Schema_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"SQL_DDL":          1,
		"DBT":              2,
	}
)

func (x Schema_Type) Enum() *Schema_Type {
	p := new(Schema_Type)
	*p = x
	return p
}

func (x Schema_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schema_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_enumTypes[1].Descriptor()
}

func (Schema_Type) Type() protoreflect.EnumType {
	return &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_enumTypes[1]
}

func (x Schema_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schema_Type.Descriptor instead.
func (Schema_Type) EnumDescriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{3, 0}
}

type DataPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Policy *Policy `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
}

func (x *DataPolicy) Reset() {
	*x = DataPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPolicy) ProtoMessage() {}

func (x *DataPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPolicy.ProtoReflect.Descriptor instead.
func (*DataPolicy) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{0}
}

func (x *DataPolicy) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *DataPolicy) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target          *Target                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	FieldTransforms []*Policy_FieldTransform `protobuf:"bytes,2,rep,name=field_transforms,json=fieldTransforms,proto3" json:"field_transforms,omitempty"`
	RowFilters      []*Policy_RowFilter      `protobuf:"bytes,3,rep,name=row_filters,json=rowFilters,proto3" json:"row_filters,omitempty"`
}

func (x *Policy) Reset() {
	*x = Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Policy) GetFieldTransforms() []*Policy_FieldTransform {
	if x != nil {
		return x.FieldTransforms
	}
	return nil
}

func (x *Policy) GetRowFilters() []*Policy_RowFilter {
	if x != nil {
		return x.RowFilters
	}
	return nil
}

type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     Target_TargetType `protobuf:"varint,1,opt,name=type,proto3,enum=strmprivacy.api.data_policies.v1alpha.Target_TargetType" json:"type,omitempty"`
	Fullname string            `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetType() Target_TargetType {
	if x != nil {
		return x.Type
	}
	return Target_TARGET_TYPE_UNSPECIFIED
}

func (x *Target) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Schema_Type `protobuf:"varint,1,opt,name=type,proto3,enum=strmprivacy.api.data_policies.v1alpha.Schema_Type" json:"type,omitempty"`
	Spec string      `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{3}
}

func (x *Schema) GetType() Schema_Type {
	if x != nil {
		return x.Type
	}
	return Schema_TYPE_UNSPECIFIED
}

func (x *Schema) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type FieldPath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldComponents []string `protobuf:"bytes,1,rep,name=field_components,json=fieldComponents,proto3" json:"field_components,omitempty"`
}

func (x *FieldPath) Reset() {
	*x = FieldPath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPath) ProtoMessage() {}

func (x *FieldPath) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPath.ProtoReflect.Descriptor instead.
func (*FieldPath) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{4}
}

func (x *FieldPath) GetFieldComponents() []string {
	if x != nil {
		return x.FieldComponents
	}
	return nil
}

type Policy_RowFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldPath  *FieldPath `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Principals []string   `protobuf:"bytes,2,rep,name=principals,proto3" json:"principals,omitempty"`
	Condition  string     `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
}

func (x *Policy_RowFilter) Reset() {
	*x = Policy_RowFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_RowFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_RowFilter) ProtoMessage() {}

func (x *Policy_RowFilter) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_RowFilter.ProtoReflect.Descriptor instead.
func (*Policy_RowFilter) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Policy_RowFilter) GetFieldPath() *FieldPath {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *Policy_RowFilter) GetPrincipals() []string {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *Policy_RowFilter) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type Policy_FieldTransform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldPath  *FieldPath                         `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Transforms []*Policy_FieldTransform_Transform `protobuf:"bytes,2,rep,name=transforms,proto3" json:"transforms,omitempty"`
}

func (x *Policy_FieldTransform) Reset() {
	*x = Policy_FieldTransform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_FieldTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_FieldTransform) ProtoMessage() {}

func (x *Policy_FieldTransform) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_FieldTransform.ProtoReflect.Descriptor instead.
func (*Policy_FieldTransform) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Policy_FieldTransform) GetFieldPath() *FieldPath {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *Policy_FieldTransform) GetTransforms() []*Policy_FieldTransform_Transform {
	if x != nil {
		return x.Transforms
	}
	return nil
}

type Policy_FieldTransform_Transform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principals []string `protobuf:"bytes,1,rep,name=principals,proto3" json:"principals,omitempty"`
	// Types that are assignable to Transform:
	//
	//	*Policy_FieldTransform_Transform_Regex
	//	*Policy_FieldTransform_Transform_Identity
	//	*Policy_FieldTransform_Transform_Fixed
	//	*Policy_FieldTransform_Transform_Hash_
	//	*Policy_FieldTransform_Transform_Udf_
	Transform isPolicy_FieldTransform_Transform_Transform `protobuf_oneof:"transform"`
}

func (x *Policy_FieldTransform_Transform) Reset() {
	*x = Policy_FieldTransform_Transform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_FieldTransform_Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_FieldTransform_Transform) ProtoMessage() {}

func (x *Policy_FieldTransform_Transform) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_FieldTransform_Transform.ProtoReflect.Descriptor instead.
func (*Policy_FieldTransform_Transform) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *Policy_FieldTransform_Transform) GetPrincipals() []string {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (m *Policy_FieldTransform_Transform) GetTransform() isPolicy_FieldTransform_Transform_Transform {
	if m != nil {
		return m.Transform
	}
	return nil
}

func (x *Policy_FieldTransform_Transform) GetRegex() *Policy_FieldTransform_Transform_RegexExtract {
	if x, ok := x.GetTransform().(*Policy_FieldTransform_Transform_Regex); ok {
		return x.Regex
	}
	return nil
}

func (x *Policy_FieldTransform_Transform) GetIdentity() bool {
	if x, ok := x.GetTransform().(*Policy_FieldTransform_Transform_Identity); ok {
		return x.Identity
	}
	return false
}

func (x *Policy_FieldTransform_Transform) GetFixed() *Policy_FieldTransform_Transform_FixedValue {
	if x, ok := x.GetTransform().(*Policy_FieldTransform_Transform_Fixed); ok {
		return x.Fixed
	}
	return nil
}

func (x *Policy_FieldTransform_Transform) GetHash() *Policy_FieldTransform_Transform_Hash {
	if x, ok := x.GetTransform().(*Policy_FieldTransform_Transform_Hash_); ok {
		return x.Hash
	}
	return nil
}

func (x *Policy_FieldTransform_Transform) GetUdf() *Policy_FieldTransform_Transform_Udf {
	if x, ok := x.GetTransform().(*Policy_FieldTransform_Transform_Udf_); ok {
		return x.Udf
	}
	return nil
}

type isPolicy_FieldTransform_Transform_Transform interface {
	isPolicy_FieldTransform_Transform_Transform()
}

type Policy_FieldTransform_Transform_Regex struct {
	Regex *Policy_FieldTransform_Transform_RegexExtract `protobuf:"bytes,2,opt,name=regex,proto3,oneof"`
}

type Policy_FieldTransform_Transform_Identity struct {
	Identity bool `protobuf:"varint,3,opt,name=identity,proto3,oneof"`
}

type Policy_FieldTransform_Transform_Fixed struct {
	Fixed *Policy_FieldTransform_Transform_FixedValue `protobuf:"bytes,4,opt,name=fixed,proto3,oneof"`
}

type Policy_FieldTransform_Transform_Hash_ struct {
	Hash *Policy_FieldTransform_Transform_Hash `protobuf:"bytes,5,opt,name=hash,proto3,oneof"`
}

type Policy_FieldTransform_Transform_Udf_ struct {
	Udf *Policy_FieldTransform_Transform_Udf `protobuf:"bytes,6,opt,name=udf,proto3,oneof"`
}

func (*Policy_FieldTransform_Transform_Regex) isPolicy_FieldTransform_Transform_Transform() {}

func (*Policy_FieldTransform_Transform_Identity) isPolicy_FieldTransform_Transform_Transform() {}

func (*Policy_FieldTransform_Transform_Fixed) isPolicy_FieldTransform_Transform_Transform() {}

func (*Policy_FieldTransform_Transform_Hash_) isPolicy_FieldTransform_Transform_Transform() {}

func (*Policy_FieldTransform_Transform_Udf_) isPolicy_FieldTransform_Transform_Transform() {}

type Policy_FieldTransform_Transform_Udf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Definition string `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *Policy_FieldTransform_Transform_Udf) Reset() {
	*x = Policy_FieldTransform_Transform_Udf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_FieldTransform_Transform_Udf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_FieldTransform_Transform_Udf) ProtoMessage() {}

func (x *Policy_FieldTransform_Transform_Udf) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_FieldTransform_Transform_Udf.ProtoReflect.Descriptor instead.
func (*Policy_FieldTransform_Transform_Udf) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 1, 0, 0}
}

func (x *Policy_FieldTransform_Transform_Udf) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type Policy_FieldTransform_Transform_Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed int64 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *Policy_FieldTransform_Transform_Hash) Reset() {
	*x = Policy_FieldTransform_Transform_Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_FieldTransform_Transform_Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_FieldTransform_Transform_Hash) ProtoMessage() {}

func (x *Policy_FieldTransform_Transform_Hash) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_FieldTransform_Transform_Hash.ProtoReflect.Descriptor instead.
func (*Policy_FieldTransform_Transform_Hash) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 1, 0, 1}
}

func (x *Policy_FieldTransform_Transform_Hash) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type Policy_FieldTransform_Transform_FixedValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Policy_FieldTransform_Transform_FixedValue) Reset() {
	*x = Policy_FieldTransform_Transform_FixedValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_FieldTransform_Transform_FixedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_FieldTransform_Transform_FixedValue) ProtoMessage() {}

func (x *Policy_FieldTransform_Transform_FixedValue) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_FieldTransform_Transform_FixedValue.ProtoReflect.Descriptor instead.
func (*Policy_FieldTransform_Transform_FixedValue) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 1, 0, 2}
}

func (x *Policy_FieldTransform_Transform_FixedValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Policy_FieldTransform_Transform_RegexExtract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regex string `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *Policy_FieldTransform_Transform_RegexExtract) Reset() {
	*x = Policy_FieldTransform_Transform_RegexExtract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Policy_FieldTransform_Transform_RegexExtract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy_FieldTransform_Transform_RegexExtract) ProtoMessage() {}

func (x *Policy_FieldTransform_Transform_RegexExtract) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy_FieldTransform_Transform_RegexExtract.ProtoReflect.Descriptor instead.
func (*Policy_FieldTransform_Transform_RegexExtract) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP(), []int{1, 1, 0, 3}
}

func (x *Policy_FieldTransform_Transform_RegexExtract) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

var File_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto protoreflect.FileDescriptor

var file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDesc = []byte{
	0x0a, 0x41, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x65, 0x73, 0x5f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x25, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x22, 0x9a, 0x01, 0x0a, 0x0a, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x45, 0x0a, 0x06, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x74, 0x72, 0x6d,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x12, 0x45, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0xfc, 0x09, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x45, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x67, 0x0a, 0x10, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x52, 0x0f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x73, 0x12, 0x58, 0x0a, 0x0b, 0x72, 0x6f, 0x77, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x52, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x0a, 0x72, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x9a, 0x01, 0x0a,
	0x09, 0x52, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x4f, 0x0a, 0x0a, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xca, 0x06, 0x0a, 0x0e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x4f, 0x0a, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12, 0x66, 0x0a,
	0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x46, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x73, 0x1a, 0xfe, 0x04, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70,
	0x61, 0x6c, 0x73, 0x12, 0x6b, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x53, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x67, 0x65, 0x78,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48, 0x00, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78,
	0x12, 0x1c, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x69,
	0x0a, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x51, 0x2e,
	0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x46, 0x69, 0x78, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64, 0x12, 0x61, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x5e, 0x0a, 0x03,
	0x75, 0x64, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x73, 0x74, 0x72, 0x6d,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x55, 0x64, 0x66, 0x48, 0x00, 0x52, 0x03, 0x75, 0x64, 0x66, 0x1a, 0x25, 0x0a, 0x03,
	0x55, 0x64, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x1a, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x1a,
	0x22, 0x0a, 0x0a, 0x46, 0x69, 0x78, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x24, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x65, 0x78, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x42, 0x0b, 0x0a, 0x09, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0xba, 0x01, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x4c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x38, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x0a, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x54, 0x41, 0x52,
	0x47, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x41, 0x54, 0x41, 0x42, 0x52,
	0x49, 0x43, 0x4b, 0x53, 0x5f, 0x44, 0x59, 0x4e, 0x41, 0x4d, 0x49, 0x43, 0x5f, 0x56, 0x49, 0x45,
	0x57, 0x10, 0x01, 0x22, 0x98, 0x01, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x46,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x73,
	0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x32, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x51, 0x4c, 0x5f,
	0x44, 0x44, 0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x42, 0x54, 0x10, 0x02, 0x22, 0x36,
	0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x10, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x82, 0x01, 0x0a, 0x28, 0x69, 0x6f, 0x2e, 0x73, 0x74,
	0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x50, 0x01, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2d, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x67, 0x6f,
	0x2f, 0x76, 0x33, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x3b, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescOnce sync.Once
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescData = file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDesc
)

func file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescGZIP() []byte {
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescOnce.Do(func() {
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescData = protoimpl.X.CompressGZIP(file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescData)
	})
	return file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDescData
}

var file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_goTypes = []interface{}{
	(Target_TargetType)(0),                               // 0: strmprivacy.api.data_policies.v1alpha.Target.TargetType
	(Schema_Type)(0),                                     // 1: strmprivacy.api.data_policies.v1alpha.Schema.Type
	(*DataPolicy)(nil),                                   // 2: strmprivacy.api.data_policies.v1alpha.DataPolicy
	(*Policy)(nil),                                       // 3: strmprivacy.api.data_policies.v1alpha.Policy
	(*Target)(nil),                                       // 4: strmprivacy.api.data_policies.v1alpha.Target
	(*Schema)(nil),                                       // 5: strmprivacy.api.data_policies.v1alpha.Schema
	(*FieldPath)(nil),                                    // 6: strmprivacy.api.data_policies.v1alpha.FieldPath
	(*Policy_RowFilter)(nil),                             // 7: strmprivacy.api.data_policies.v1alpha.Policy.RowFilter
	(*Policy_FieldTransform)(nil),                        // 8: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform
	(*Policy_FieldTransform_Transform)(nil),              // 9: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform
	(*Policy_FieldTransform_Transform_Udf)(nil),          // 10: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.Udf
	(*Policy_FieldTransform_Transform_Hash)(nil),         // 11: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.Hash
	(*Policy_FieldTransform_Transform_FixedValue)(nil),   // 12: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.FixedValue
	(*Policy_FieldTransform_Transform_RegexExtract)(nil), // 13: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.RegexExtract
}
var file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_depIdxs = []int32{
	5,  // 0: strmprivacy.api.data_policies.v1alpha.DataPolicy.schema:type_name -> strmprivacy.api.data_policies.v1alpha.Schema
	3,  // 1: strmprivacy.api.data_policies.v1alpha.DataPolicy.policy:type_name -> strmprivacy.api.data_policies.v1alpha.Policy
	4,  // 2: strmprivacy.api.data_policies.v1alpha.Policy.target:type_name -> strmprivacy.api.data_policies.v1alpha.Target
	8,  // 3: strmprivacy.api.data_policies.v1alpha.Policy.field_transforms:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform
	7,  // 4: strmprivacy.api.data_policies.v1alpha.Policy.row_filters:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.RowFilter
	0,  // 5: strmprivacy.api.data_policies.v1alpha.Target.type:type_name -> strmprivacy.api.data_policies.v1alpha.Target.TargetType
	1,  // 6: strmprivacy.api.data_policies.v1alpha.Schema.type:type_name -> strmprivacy.api.data_policies.v1alpha.Schema.Type
	6,  // 7: strmprivacy.api.data_policies.v1alpha.Policy.RowFilter.field_path:type_name -> strmprivacy.api.data_policies.v1alpha.FieldPath
	6,  // 8: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.field_path:type_name -> strmprivacy.api.data_policies.v1alpha.FieldPath
	9,  // 9: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.transforms:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform
	13, // 10: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.regex:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.RegexExtract
	12, // 11: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.fixed:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.FixedValue
	11, // 12: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.hash:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.Hash
	10, // 13: strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.udf:type_name -> strmprivacy.api.data_policies.v1alpha.Policy.FieldTransform.Transform.Udf
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_init() }
func file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_init() {
	if File_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldPath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_RowFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_FieldTransform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_FieldTransform_Transform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_FieldTransform_Transform_Udf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_FieldTransform_Transform_Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_FieldTransform_Transform_FixedValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Policy_FieldTransform_Transform_RegexExtract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Policy_FieldTransform_Transform_Regex)(nil),
		(*Policy_FieldTransform_Transform_Identity)(nil),
		(*Policy_FieldTransform_Transform_Fixed)(nil),
		(*Policy_FieldTransform_Transform_Hash_)(nil),
		(*Policy_FieldTransform_Transform_Udf_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_goTypes,
		DependencyIndexes: file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_depIdxs,
		EnumInfos:         file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_enumTypes,
		MessageInfos:      file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_msgTypes,
	}.Build()
	File_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto = out.File
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_rawDesc = nil
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_goTypes = nil
	file_strmprivacy_api_data_policies_v1alpha_data_policies_v1alpha_proto_depIdxs = nil
}
