// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: strmprivacy/api/onboarding/v1/onboarding_v1.proto

package onboarding

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OnboardingServiceClient is the client API for OnboardingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnboardingServiceClient interface {
	PopulateOnboardingProject(ctx context.Context, in *PopulateOnboardingProjectRequest, opts ...grpc.CallOption) (*PopulateOnboardingProjectResponse, error)
}

type onboardingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardingServiceClient(cc grpc.ClientConnInterface) OnboardingServiceClient {
	return &onboardingServiceClient{cc}
}

func (c *onboardingServiceClient) PopulateOnboardingProject(ctx context.Context, in *PopulateOnboardingProjectRequest, opts ...grpc.CallOption) (*PopulateOnboardingProjectResponse, error) {
	out := new(PopulateOnboardingProjectResponse)
	err := c.cc.Invoke(ctx, "/strmprivacy.api.onboarding.v1.OnboardingService/PopulateOnboardingProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardingServiceServer is the server API for OnboardingService service.
// All implementations should embed UnimplementedOnboardingServiceServer
// for forward compatibility
type OnboardingServiceServer interface {
	PopulateOnboardingProject(context.Context, *PopulateOnboardingProjectRequest) (*PopulateOnboardingProjectResponse, error)
}

// UnimplementedOnboardingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOnboardingServiceServer struct {
}

func (UnimplementedOnboardingServiceServer) PopulateOnboardingProject(context.Context, *PopulateOnboardingProjectRequest) (*PopulateOnboardingProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopulateOnboardingProject not implemented")
}

// UnsafeOnboardingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardingServiceServer will
// result in compilation errors.
type UnsafeOnboardingServiceServer interface {
	mustEmbedUnimplementedOnboardingServiceServer()
}

func RegisterOnboardingServiceServer(s grpc.ServiceRegistrar, srv OnboardingServiceServer) {
	s.RegisterService(&OnboardingService_ServiceDesc, srv)
}

func _OnboardingService_PopulateOnboardingProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopulateOnboardingProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingServiceServer).PopulateOnboardingProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strmprivacy.api.onboarding.v1.OnboardingService/PopulateOnboardingProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingServiceServer).PopulateOnboardingProject(ctx, req.(*PopulateOnboardingProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnboardingService_ServiceDesc is the grpc.ServiceDesc for OnboardingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnboardingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "strmprivacy.api.onboarding.v1.OnboardingService",
	HandlerType: (*OnboardingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PopulateOnboardingProject",
			Handler:    _OnboardingService_PopulateOnboardingProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strmprivacy/api/onboarding/v1/onboarding_v1.proto",
}
