// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: strmprivacy/api/rtbf/v1/rtbf_v1.proto

package rtbf

import (
	_ "github.com/strmprivacy/api-definitions-go/v2/api/entities/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
//Retrieve all key links associated with certain data owner(s)
type GetKeyLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataOwnerId []string `protobuf:"bytes,1,rep,name=data_owner_id,json=dataOwnerId,proto3" json:"data_owner_id,omitempty"`
}

func (x *GetKeyLinksRequest) Reset() {
	*x = GetKeyLinksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeyLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyLinksRequest) ProtoMessage() {}

func (x *GetKeyLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyLinksRequest.ProtoReflect.Descriptor instead.
func (*GetKeyLinksRequest) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GetKeyLinksRequest) GetDataOwnerId() []string {
	if x != nil {
		return x.DataOwnerId
	}
	return nil
}

//*
//returns a list of data owners with their associated key links and their
//expiry.
type GetKeyLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyLinks []*KeyLinks `protobuf:"bytes,1,rep,name=key_links,json=keyLinks,proto3" json:"key_links,omitempty"`
}

func (x *GetKeyLinksResponse) Reset() {
	*x = GetKeyLinksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeyLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyLinksResponse) ProtoMessage() {}

func (x *GetKeyLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyLinksResponse.ProtoReflect.Descriptor instead.
func (*GetKeyLinksResponse) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyLinksResponse) GetKeyLinks() []*KeyLinks {
	if x != nil {
		return x.KeyLinks
	}
	return nil
}

//* called by an entity that can create key link(s)
//typically (but not necessarily) only one key link is added at the same time.
type AddKeyLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyLink *KeyLinks `protobuf:"bytes,1,opt,name=key_link,json=keyLink,proto3" json:"key_link,omitempty"`
}

func (x *AddKeyLinkRequest) Reset() {
	*x = AddKeyLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddKeyLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyLinkRequest) ProtoMessage() {}

func (x *AddKeyLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyLinkRequest.ProtoReflect.Descriptor instead.
func (*AddKeyLinkRequest) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP(), []int{2}
}

func (x *AddKeyLinkRequest) GetKeyLink() *KeyLinks {
	if x != nil {
		return x.KeyLink
	}
	return nil
}

type AddKeyLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddKeyLinkResponse) Reset() {
	*x = AddKeyLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddKeyLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyLinkResponse) ProtoMessage() {}

func (x *AddKeyLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyLinkResponse.ProtoReflect.Descriptor instead.
func (*AddKeyLinkResponse) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP(), []int{3}
}

//* one data owner 0 or more key links, each of which could have
//been used to encrypt data up to a certain point in time.
type KeyLinks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataOwner         string                        `protobuf:"bytes,1,opt,name=data_owner,json=dataOwner,proto3" json:"data_owner,omitempty"`
	KeysAndTimestamps []*KeyLinks_KeysAndTimestamps `protobuf:"bytes,2,rep,name=keys_and_timestamps,json=keysAndTimestamps,proto3" json:"keys_and_timestamps,omitempty"`
}

func (x *KeyLinks) Reset() {
	*x = KeyLinks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyLinks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLinks) ProtoMessage() {}

func (x *KeyLinks) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLinks.ProtoReflect.Descriptor instead.
func (*KeyLinks) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP(), []int{4}
}

func (x *KeyLinks) GetDataOwner() string {
	if x != nil {
		return x.DataOwner
	}
	return ""
}

func (x *KeyLinks) GetKeysAndTimestamps() []*KeyLinks_KeysAndTimestamps {
	if x != nil {
		return x.KeysAndTimestamps
	}
	return nil
}

type KeyLinks_KeysAndTimestamps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyLink    string                 `protobuf:"bytes,1,opt,name=key_link,json=keyLink,proto3" json:"key_link,omitempty"`
	ExpiryTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
}

func (x *KeyLinks_KeysAndTimestamps) Reset() {
	*x = KeyLinks_KeysAndTimestamps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyLinks_KeysAndTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLinks_KeysAndTimestamps) ProtoMessage() {}

func (x *KeyLinks_KeysAndTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLinks_KeysAndTimestamps.ProtoReflect.Descriptor instead.
func (*KeyLinks_KeysAndTimestamps) Descriptor() ([]byte, []int) {
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP(), []int{4, 0}
}

func (x *KeyLinks_KeysAndTimestamps) GetKeyLink() string {
	if x != nil {
		return x.KeyLink
	}
	return ""
}

func (x *KeyLinks_KeysAndTimestamps) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

var File_strmprivacy_api_rtbf_v1_rtbf_v1_proto protoreflect.FileDescriptor

var file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x74, 0x62, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x74, 0x62, 0x66, 0x5f, 0x76,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74, 0x62, 0x66, 0x2e, 0x76, 0x31,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x2d, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x55, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x69, 0x6e, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74, 0x62, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x22, 0x51, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4b, 0x65, 0x79, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x6b, 0x65, 0x79,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x74,
	0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74,
	0x62, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4b, 0x65,
	0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x80, 0x02,
	0x0a, 0x08, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x22, 0x0a, 0x0a, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03,
	0xe0, 0x41, 0x02, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x63,
	0x0a, 0x13, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x73, 0x74,
	0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74,
	0x62, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x4b,
	0x65, 0x79, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73,
	0x52, 0x11, 0x6b, 0x65, 0x79, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x1a, 0x6b, 0x0a, 0x11, 0x4b, 0x65, 0x79, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x3b, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x32, 0xde, 0x01, 0x0a, 0x0b, 0x52, 0x74, 0x62, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x68, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12,
	0x2b, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x74, 0x62, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73,
	0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x74, 0x62, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x2a, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74, 0x62, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74, 0x62, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x5d, 0x0a, 0x1a, 0x69, 0x6f, 0x2e, 0x73, 0x74, 0x72, 0x6d, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x74, 0x62, 0x66, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74,
	0x72, 0x6d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x32, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x72, 0x74, 0x62, 0x66, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x74, 0x62, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescOnce sync.Once
	file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescData = file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDesc
)

func file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescGZIP() []byte {
	file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescOnce.Do(func() {
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescData)
	})
	return file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDescData
}

var file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_goTypes = []interface{}{
	(*GetKeyLinksRequest)(nil),         // 0: strmprivacy.api.rtbf.v1.GetKeyLinksRequest
	(*GetKeyLinksResponse)(nil),        // 1: strmprivacy.api.rtbf.v1.GetKeyLinksResponse
	(*AddKeyLinkRequest)(nil),          // 2: strmprivacy.api.rtbf.v1.AddKeyLinkRequest
	(*AddKeyLinkResponse)(nil),         // 3: strmprivacy.api.rtbf.v1.AddKeyLinkResponse
	(*KeyLinks)(nil),                   // 4: strmprivacy.api.rtbf.v1.KeyLinks
	(*KeyLinks_KeysAndTimestamps)(nil), // 5: strmprivacy.api.rtbf.v1.KeyLinks.KeysAndTimestamps
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_depIdxs = []int32{
	4, // 0: strmprivacy.api.rtbf.v1.GetKeyLinksResponse.key_links:type_name -> strmprivacy.api.rtbf.v1.KeyLinks
	4, // 1: strmprivacy.api.rtbf.v1.AddKeyLinkRequest.key_link:type_name -> strmprivacy.api.rtbf.v1.KeyLinks
	5, // 2: strmprivacy.api.rtbf.v1.KeyLinks.keys_and_timestamps:type_name -> strmprivacy.api.rtbf.v1.KeyLinks.KeysAndTimestamps
	6, // 3: strmprivacy.api.rtbf.v1.KeyLinks.KeysAndTimestamps.expiry_time:type_name -> google.protobuf.Timestamp
	0, // 4: strmprivacy.api.rtbf.v1.RtbfService.GetKeyLinks:input_type -> strmprivacy.api.rtbf.v1.GetKeyLinksRequest
	2, // 5: strmprivacy.api.rtbf.v1.RtbfService.AddKeyLink:input_type -> strmprivacy.api.rtbf.v1.AddKeyLinkRequest
	1, // 6: strmprivacy.api.rtbf.v1.RtbfService.GetKeyLinks:output_type -> strmprivacy.api.rtbf.v1.GetKeyLinksResponse
	3, // 7: strmprivacy.api.rtbf.v1.RtbfService.AddKeyLink:output_type -> strmprivacy.api.rtbf.v1.AddKeyLinkResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_init() }
func file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_init() {
	if File_strmprivacy_api_rtbf_v1_rtbf_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeyLinksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeyLinksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddKeyLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddKeyLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyLinks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyLinks_KeysAndTimestamps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_goTypes,
		DependencyIndexes: file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_depIdxs,
		MessageInfos:      file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_msgTypes,
	}.Build()
	File_strmprivacy_api_rtbf_v1_rtbf_v1_proto = out.File
	file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_rawDesc = nil
	file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_goTypes = nil
	file_strmprivacy_api_rtbf_v1_rtbf_v1_proto_depIdxs = nil
}
